### ISSUE TITLE
Doesn't work on some files exported from Musescore

### ISSUE THREAD

**Issue by IvanKozar** [MrRedBeard/DotNet-MXL-Parsing-for-Arduino#4]
Hi, 
The MusicXMLParser.exe breaks when I try to convert certain mxl or xml files exported form musescore. I get this error from windows: 
************** Exception Text **************
System.NullReferenceException: Object reference not set to an instance of an object.
   at MusicXMLParser.FormMain.LoadMXL(String xml)
   at MusicXMLParser.FormMain.buttonOpenFile_Click(Object sender, EventArgs e)
   at System.Windows.Forms.Control.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnMouseUp(MouseEventArgs mevent)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ButtonBase.WndProc(Message& m)
   at System.Windows.Forms.Button.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

It works if I download your example file, modify it and then save it, it works again. However, when I try to load midi file to Musescore, deleting all voices except one, and then save it as xml/mxl, it doesnt work anymore. I don't know if there is something else I should be watching at, maybe some setting not set correctly or something. 

I was also using your MusicMXLParser.exe last summer and it worked flawlessly, but I noticed the new version has been uploaded in January. Is there any way to get the old version back or to fix this?
Thanks :)

**Comment by IvanKozar** [comment]
Sometimes I also get this: 

************** Exception Text **************
System.Xml.XmlException: There are multiple root elements. Line 2, position 2.
   at System.Xml.XmlTextReaderImpl.Throw(Exception e)
   at System.Xml.XmlTextReaderImpl.Throw(String res, String arg)
   at System.Xml.XmlTextReaderImpl.ParseDocumentContent()
   at System.Xml.XmlTextReaderImpl.Read()
   at System.Xml.XmlLoader.LoadNode(Boolean skipOverWhitespace)
   at System.Xml.XmlLoader.LoadDocSequence(XmlDocument parentDoc)
   at System.Xml.XmlLoader.Load(XmlDocument doc, XmlReader reader, Boolean preserveWhitespace)
   at System.Xml.XmlDocument.Load(XmlReader reader)
   at System.Xml.XmlDocument.LoadXml(String xml)
   at MusicXMLParser.FormMain.LoadMXL(String xml)
   at MusicXMLParser.FormMain.buttonOpenFile_Click(Object sender, EventArgs e)
   at System.Windows.Forms.Control.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnMouseUp(MouseEventArgs mevent)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ButtonBase.WndProc(Message& m)
   at System.Windows.Forms.Button.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

**Comment by MrRedBeard** [comment]
Can you post links to songs that do this? I'll be traveling so it might be a bit before I can take a solid look.

**Comment by IvanKozar** [comment]
Sure, for now I only have this one, will post more as I get back to testing. 
https://ferhr-my.sharepoint.com/:u:/g/personal/ik49908_fer_hr/ETjRuzVcsghMhy9UycMzadwBD4o1OT7bOZYeK9-mcvdL2A?e=L5gP3I

**Comment by melqui-andrade** [comment]
I've had a problem like that. It was caused by this condicional: 

`if (xmlDoc.DocumentElement.SelectSingleNode("/score-partwise/part/measure/direction/sound").Attributes["tempo"].Value != null)`

some xml files don't have the "tempo" attribute, so a exception is thrown. I've just put that condicional in a try/catch and it works =D

**Comment by ranroun3** [comment]
Are there any updates on this? I tried adding a try-catch in the MainForm.cs, but I'm still running into errors
`try{
                    tempo = Math.Round(Convert.ToDouble(xmlDoc.DocumentElement.SelectSingleNode("/score-partwise/part/measure/direction/sound").Attributes["tempo"].Value.Trim(' ')));
            }
            catch(NullReferenceException){
                tempo = 30;
            }`

**Comment by MrRedBeard** [comment]
Fixed
